server:
  port: 8080

spring:
  main.banner-mode: off
  jpa:
    open-in-view: false
    hibernate:
        ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
  flyway.enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test10
    username: root
    password: root
    config:
      poolName: "rezt"
      connection-timeout: 3000 # Default: 30000 (30 seconds)
      maximum-pool-size: 15 # Default: 10
      minimumIdle: 5  # Default: same as maximum-pool-size
      maxLifetime: 600000 # Default: 1800000 (30 minutes)
      connectionInitSql: "SELECT 1" # Default: none

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.*: DEBUG
    org.hibernate: ERROR
